#!/usr/bin/env python3
"""Summarise a results/<date>_instruction_profile directory.

* DSO / symbol shares of the full inference (which library runs the time)
* For each operator: hottest symbols and an instruction mix of its hottest
  symbol, both weighted by samples (where cycles land) and static (what the
  code consists of). Mnemonics are classified into loads, stores, FMA,
  other vector arithmetic, shuffles, scalar FP, integer/address, branches,
  prefetches, ... with vector width taken from register names.
* perf mem: load samples by data source (L1 / LFB / L2 / L3 / RAM) with the
  sampled load latency (weight).

Sampling caveat (documented in REPORT.md): with cycles:P the sample is often
attributed to the instruction that was waiting or to the next one; heavy
sample counts on an instruction right after a load usually mean "waiting on
that load".
"""
import collections
import json
import re
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import plotstyle as ps  # noqa: E402
from matplotlib import pyplot as plt  # noqa: E402

LINE = re.compile(r"^\s*([\d.]+)\s*:\s*([0-9a-f]+):\s+([a-z][\w.]*)\s*(.*)$")
CLASSES = ["fma", "vec_arith", "vec_load", "vec_store", "broadcast", "shuffle/permute", "compare/mask",
           "scalar_fp", "int/addr", "gpr_load", "gpr_store", "branch", "prefetch", "other"]


def width(ops: str) -> str:
    return "zmm" if "zmm" in ops else "ymm" if "ymm" in ops else "xmm" if "xmm" in ops else ""


def classify(mn: str, ops: str) -> str:
    mem = "PTR" in ops or "[" in ops
    first = ops.split(",")[0] if ops else ""
    if mn.startswith("prefetch"):
        return "prefetch"
    if mn.startswith("j") or mn in ("call", "ret", "loop"):
        return "branch"
    if re.match(r"v?f(n)?m(add|sub)", mn):
        return "fma"
    if mn.startswith("vbroadcast") or mn.startswith("vpbroadcast"):
        return "broadcast"
    if re.match(r"v(mov|lddqu)", mn) and width(ops):
        if mem and ("PTR" in first or "[" in first):
            return "vec_store"
        if mem:
            return "vec_load"
        return "shuffle/permute"
    if re.match(r"v(perm|shuf|unpck|punpck|align|extract|insert|pshuf|blend|pblend|compress|expand)", mn):
        return "shuffle/permute"
    if re.match(r"(v)?(u)?comis|vcmp|vpcmp|k(mov|or|and|not|shift|test|unpck)", mn):
        return "compare/mask"
    if re.match(r"v?(add|sub|mul|div|max|min|sqrt)s[sd]$|v?cvt", mn):
        return "scalar_fp"
    if mn.startswith("v") and width(ops):
        return "vec_arith"
    if mn in ("mov", "movsxd", "movzx", "movsx") and mem:
        return "gpr_store" if ("PTR" in first or "[" in first) else "gpr_load"
    if re.match(r"(add|sub|lea|inc|dec|cmp|test|imul|shl|shr|sar|and|or|xor|mov|cmov|sete|setne|neg|not)", mn):
        return "int/addr"
    return "other"


def parse_annotate(path: Path):
    rows = []
    for line in path.read_text(errors="replace").splitlines():
        m = LINE.match(line)
        if m:
            pct, addr, mn, ops = float(m.group(1)), m.group(2), m.group(3), m.group(4)
            rows.append({"pct": pct, "addr": addr, "mnemonic": mn, "operands": ops.strip(),
                         "class": classify(mn, ops), "width": width(ops)})
    return pd.DataFrame(rows)


def parse_shares(path: Path, key_fields: int):
    out = []
    if not path.exists():
        return out
    for line in path.read_text(errors="replace").splitlines():
        m = re.match(r"^\s*([\d.]+)%\s+(.*?)\s*$", line)
        if m:
            out.append((float(m.group(1)), m.group(2)))
    return out


def parse_mem_samples(path: Path):
    """perf script -F event,period,weight,data_src lines -> per-level table."""
    if not path.exists():
        return None
    pat = re.compile(r"\s*(\d+)\s+\S+:\s+\S+\s+\|OP (\S+)\|LVL ([^|]+)\|.*\|BLK\s+(.*?)\s+(\d+)\s*$")
    agg = collections.defaultdict(lambda: [0, 0, 0])
    for line in path.read_text(errors="replace").splitlines():
        m = pat.match(line)
        if m:
            period, level, lat = int(m.group(1)), m.group(3).strip(), int(m.group(5))
            a = agg[level]
            a[0] += 1
            a[1] += period
            a[2] += period * lat
    if not agg:
        return None
    tp = sum(a[1] for a in agg.values())
    tw = sum(a[2] for a in agg.values())
    rows = [{"data source": k, "samples": a[0], "share of loads %": 100 * a[1] / tp,
             "mean latency (cycles)": a[2] / a[1], "share of latency %": 100 * a[2] / tw}
            for k, a in agg.items()]
    return pd.DataFrame(rows).sort_values("share of loads %", ascending=False)


def main(out_dir):
    out = Path(out_dir)
    proc, plots = out / "processed", out / "plots"
    proc.mkdir(exist_ok=True)
    plots.mkdir(exist_ok=True)
    L = ["# Instruction-level profile", "",
         "Generated by `analysis/analyze_instructions.py` from perf record (cycles:P, LBR call stacks) "
         "with oneDNN JIT code resolved via jitdump. Percentages are shares of cycle samples.", ""]

    dso = parse_shares(out / "raw" / "full_dso.txt", 1)
    L += ["## Full inference: share of samples by shared object", "", "| % samples | DSO |", "|---|---|"]
    L += [f"| {p:.2f} | `{d}` |" for p, d in dso[:15]]
    sym = parse_shares(out / "raw" / "full_symbols.txt", 2)
    L += ["", "## Full inference: hottest symbols", "", "| % samples | DSO / symbol |", "|---|---|"]
    L += [f"| {p:.2f} | `{s[:150]}` |" for p, s in sym[:30]]
    L.append("")

    mixes = {}
    for ann in sorted((out / "annotate").glob("*_0.annotate.txt")):
        layer = ann.name[: -len("_0.annotate.txt")]
        df = parse_annotate(ann)
        if df.empty:
            continue
        head = ann.read_text().splitlines()[:3]
        symname = head[0].replace("# symbol: ", "")
        share = head[2].replace("# share of operator samples: ", "")
        df.to_csv(proc / f"annotate_{layer}.csv", index=False)
        w = df.groupby("class")["pct"].sum()
        s = df.groupby("class").size() / len(df) * 100
        wid = df[df["class"].isin(["fma", "vec_arith", "vec_load", "vec_store"])].groupby("width").size()
        vec = df[df["class"].isin(["fma", "vec_arith", "vec_load", "vec_store", "broadcast", "shuffle/permute"])]
        widw = vec.groupby("width")["pct"].sum()
        mixes[layer] = {"symbol": symname, "symbol_share": share, "weighted": w.to_dict(), "static": s.to_dict(),
                        "vector_widths_static": wid.to_dict(), "vector_widths_weighted": widw.to_dict(),
                        "n_instructions": len(df)}
        top = df.sort_values("pct", ascending=False).head(12)
        L += [f"## Operator `{layer}`", "", f"Hottest symbol ({share} of this operator's samples): `{symname[:160]}`", "",
              f"Static size {len(df)} instructions; vector instructions by width (static): "
              + ", ".join(f"{k or 'none'}={v}" for k, v in wid.to_dict().items()), "",
              "| class | % of samples (weighted) | % of instructions (static) |", "|---|---|---|"]
        for c in CLASSES:
            if c in w.index or c in s.index:
                L.append(f"| {c} | {w.get(c, 0):.1f} | {s.get(c, 0):.1f} |")
        L += ["", "Hottest instructions:", "", "| % | address | instruction |", "|---|---|---|"]
        L += [f"| {r.pct:.2f} | {r.addr} | `{r.mnemonic} {r.operands[:70]}` |" for r in top.itertuples()]
        L.append("")
    (proc / "instruction_mix.json").write_text(json.dumps(mixes, indent=2) + "\n")

    if mixes:
        # Order: convolutions/GEMMs first, then the memory/elementwise ops.
        order = ["conv1", "layer1.0.conv1", "layer1.0.conv2", "layer1.0.conv3", "layer2.0.downsample.0",
                 "layer4.0.conv2", "fc", "layer1.0.bn1", "layer1.0.relu1", "layer1.0.add", "avgpool", "maxpool"]
        layers = [l for l in order if l in mixes] + [l for l in mixes if l not in order]
        fig, ax = plt.subplots(figsize=(10.5, 0.55 * len(layers) + 2.0))
        # Fewer, semantic groups so every group gets a distinct colour.
        groups = [("vector FMA", ["fma"], ps.CAT[0]),
                  ("other vector math", ["vec_arith", "shuffle/permute", "compare/mask"], ps.CAT[4]),
                  ("vector load / broadcast", ["vec_load", "broadcast"], ps.CAT[1]),
                  ("vector store", ["vec_store"], ps.CAT[3]),
                  ("scalar FP", ["scalar_fp"], ps.CAT[6]),
                  ("integer load/store (GPR)", ["gpr_load", "gpr_store"], ps.CAT[7]),
                  ("integer / address math", ["int/addr"], ps.CAT[2]),
                  ("branch", ["branch"], ps.NEUTRAL),
                  ("prefetch / other", ["prefetch", "other"], "#d9d8d3")]
        import numpy as np
        left = np.zeros(len(layers))
        y = np.arange(len(layers))[::-1]
        for label, cls, color in groups:
            vals = np.array([sum(mixes[l]["weighted"].get(c, 0) for c in cls) for l in layers])
            ax.barh(y, vals, left=left, color=color, label=label, height=0.62, edgecolor=ps.SURFACE, linewidth=1)
            left += vals
        # Vector register width carrying most of the hot symbol's vector-instruction samples.
        for yi, l in zip(y, layers):
            wid = {k: v for k, v in mixes[l]["vector_widths_weighted"].items() if k}
            tag = max(wid, key=wid.get) if wid else "scalar"
            tag = {"zmm": "zmm (AVX-512)", "ymm": "ymm (AVX2)", "xmm": "xmm/scalar"}.get(tag, tag)
            ax.text(101.5, yi, tag, va="center", fontsize=8.5, color=ps.TEXT2 if hasattr(ps, "TEXT2") else "#555")
        ax.set_yticks(y)
        ax.set_yticklabels(layers)
        ax.set_xlim(0, 100)
        ax.set_xlabel("% of cycle samples in the operator's hottest symbol")
        ps.titled(ax, "Which instructions the cycles land on, per operator",
                  "perf annotate (cycles:P) of each standalone operator's hottest symbol; right: register width "
                  "of the vector instructions the samples land on")
        ax.legend(ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.12))
        fig.savefig(plots / "instruction_mix_by_operator.png")
        plt.close(fig)

    # perf mem. The recording has two events: cpu/mem-loads-aux/ (group
    # leader, no data source: perf reports it as a separate 100% 'N/A' block)
    # and cpu/mem-loads,ldlat=30/. Samples are frequency-based (variable
    # period), so shares are period-weighted: estimated share of eligible loads.
    mem = parse_mem_samples(out / "raw" / "mem_samples.txt")
    if mem is not None:
        L += ["## perf mem: sampled loads by data source (full inference)", "",
              "PEBS load-latency sampling (`cpu/mem-loads,ldlat=30/`), parsed per sample from "
              "`raw/mem_samples.txt` (`perf script`). 'share of loads' is period-weighted (estimated share "
              "of eligible loads), 'share of latency' weights each load by its sampled latency. "
              "The ldlat filter makes this a sample of SLOW loads: the counters (mem_load_retired) show "
              ">95% of all loads hit L1; L1 hits still appear here (with ~5-9 cycle latency) because the "
              "PMU does not apply the threshold to every sample. 'LFB/MAB hit' = the line was already "
              "being fetched (miss in flight, often a prefetch that has not arrived).", "",
              mem.round(1).to_markdown(index=False), ""]
    (proc / "INSTRUCTIONS.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[:80]))


if __name__ == "__main__":
    main(sys.argv[1])
