#!/usr/bin/env python3
"""Summarise a results/<date>_instruction_profile directory.

* DSO / symbol shares of the full inference (which library runs the time)
* For each operator: hottest symbols and an instruction mix of its hottest
  symbol, both weighted by samples (where cycles land) and static (what the
  code consists of). Mnemonics are classified into loads, stores, FMA,
  other vector arithmetic, shuffles, scalar FP, integer/address, branches,
  prefetches, ... with vector width taken from register names.
* perf mem: load samples by data source (L1 / LFB / L2 / L3 / RAM) with the
  sampled load latency (weight).

Sampling caveat (documented in REPORT.md): with cycles:P the sample is often
attributed to the instruction that was waiting or to the next one; heavy
sample counts on an instruction right after a load usually mean "waiting on
that load".
"""
import collections
import json
import re
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import plotstyle as ps  # noqa: E402
from matplotlib import pyplot as plt  # noqa: E402

LINE = re.compile(r"^\s*([\d.]+)\s*:\s*([0-9a-f]+):\s+([a-z][\w.]*)\s*(.*)$")
CLASSES = ["fma", "vec_arith", "vec_load", "vec_store", "broadcast", "shuffle/permute", "compare/mask",
           "scalar_fp", "int/addr", "gpr_load", "gpr_store", "branch", "prefetch", "other"]


def width(ops: str) -> str:
    return "zmm" if "zmm" in ops else "ymm" if "ymm" in ops else "xmm" if "xmm" in ops else ""


def classify(mn: str, ops: str) -> str:
    mem = "PTR" in ops or "[" in ops
    first = ops.split(",")[0] if ops else ""
    if mn.startswith("prefetch"):
        return "prefetch"
    if mn.startswith("j") or mn in ("call", "ret", "loop"):
        return "branch"
    if re.match(r"v?f(n)?m(add|sub)", mn):
        return "fma"
    if mn.startswith("vbroadcast") or mn.startswith("vpbroadcast"):
        return "broadcast"
    if re.match(r"v(mov|lddqu)", mn) and width(ops):
        if mem and ("PTR" in first or "[" in first):
            return "vec_store"
        if mem:
            return "vec_load"
        return "shuffle/permute"
    if re.match(r"v(perm|shuf|unpck|punpck|align|extract|insert|pshuf|blend|pblend|compress|expand)", mn):
        return "shuffle/permute"
    if re.match(r"(v)?(u)?comis|vcmp|vpcmp|k(mov|or|and|not|shift|test|unpck)", mn):
        return "compare/mask"
    if re.match(r"v?(add|sub|mul|div|max|min|sqrt)s[sd]$|v?cvt", mn):
        return "scalar_fp"
    if mn.startswith("v") and width(ops):
        return "vec_arith"
    if mn in ("mov", "movsxd", "movzx", "movsx") and mem:
        return "gpr_store" if ("PTR" in first or "[" in first) else "gpr_load"
    if re.match(r"(add|sub|lea|inc|dec|cmp|test|imul|shl|shr|sar|and|or|xor|mov|cmov|sete|setne|neg|not)", mn):
        return "int/addr"
    return "other"


def parse_annotate(path: Path):
    rows = []
    for line in path.read_text(errors="replace").splitlines():
        m = LINE.match(line)
        if m:
            pct, addr, mn, ops = float(m.group(1)), m.group(2), m.group(3), m.group(4)
            rows.append({"pct": pct, "addr": addr, "mnemonic": mn, "operands": ops.strip(),
                         "class": classify(mn, ops), "width": width(ops)})
    return pd.DataFrame(rows)


def parse_shares(path: Path, key_fields: int):
    out = []
    if not path.exists():
        return out
    for line in path.read_text(errors="replace").splitlines():
        m = re.match(r"^\s*([\d.]+)%\s+(.*?)\s*$", line)
        if m:
            out.append((float(m.group(1)), m.group(2)))
    return out


def main(out_dir):
    out = Path(out_dir)
    proc, plots = out / "processed", out / "plots"
    proc.mkdir(exist_ok=True)
    plots.mkdir(exist_ok=True)
    L = ["# Instruction-level profile", "",
         "Generated by `analysis/analyze_instructions.py` from perf record (cycles:P, LBR call stacks) "
         "with oneDNN JIT code resolved via jitdump. Percentages are shares of cycle samples.", ""]

    dso = parse_shares(out / "raw" / "full_dso.txt", 1)
    L += ["## Full inference: share of samples by shared object", "", "| % samples | DSO |", "|---|---|"]
    L += [f"| {p:.2f} | `{d}` |" for p, d in dso[:15]]
    sym = parse_shares(out / "raw" / "full_symbols.txt", 2)
    L += ["", "## Full inference: hottest symbols", "", "| % samples | DSO / symbol |", "|---|---|"]
    L += [f"| {p:.2f} | `{s[:150]}` |" for p, s in sym[:30]]
    L.append("")

    mixes = {}
    for ann in sorted((out / "annotate").glob("*_0.annotate.txt")):
        layer = ann.name[: -len("_0.annotate.txt")]
        df = parse_annotate(ann)
        if df.empty:
            continue
        head = ann.read_text().splitlines()[:3]
        symname = head[0].replace("# symbol: ", "")
        share = head[2].replace("# share of operator samples: ", "")
        df.to_csv(proc / f"annotate_{layer}.csv", index=False)
        w = df.groupby("class")["pct"].sum()
        s = df.groupby("class").size() / len(df) * 100
        wid = df[df["class"].isin(["fma", "vec_arith", "vec_load", "vec_store"])].groupby("width").size()
        mixes[layer] = {"symbol": symname, "symbol_share": share, "weighted": w.to_dict(), "static": s.to_dict(),
                        "vector_widths_static": wid.to_dict(), "n_instructions": len(df)}
        top = df.sort_values("pct", ascending=False).head(12)
        L += [f"## Operator `{layer}`", "", f"Hottest symbol ({share} of this operator's samples): `{symname[:160]}`", "",
              f"Static size {len(df)} instructions; vector instructions by width (static): "
              + ", ".join(f"{k or 'none'}={v}" for k, v in wid.to_dict().items()), "",
              "| class | % of samples (weighted) | % of instructions (static) |", "|---|---|---|"]
        for c in CLASSES:
            if c in w.index or c in s.index:
                L.append(f"| {c} | {w.get(c, 0):.1f} | {s.get(c, 0):.1f} |")
        L += ["", "Hottest instructions:", "", "| % | address | instruction |", "|---|---|---|"]
        L += [f"| {r.pct:.2f} | {r.addr} | `{r.mnemonic} {r.operands[:70]}` |" for r in top.itertuples()]
        L.append("")
    (proc / "instruction_mix.json").write_text(json.dumps(mixes, indent=2) + "\n")

    if mixes:
        layers = list(mixes)
        fig, ax = plt.subplots(figsize=(10, 0.55 * len(layers) + 1.8))
        show = ["fma", "vec_load", "broadcast", "vec_store", "vec_arith", "shuffle/permute", "scalar_fp",
                "int/addr", "branch"]
        import numpy as np
        left = np.zeros(len(layers))
        y = np.arange(len(layers))[::-1]
        for i, c in enumerate(show):
            vals = np.array([mixes[l]["weighted"].get(c, 0) for l in layers])
            color = ps.CAT[i] if i < 8 else ps.NEUTRAL
            ax.barh(y, vals, left=left, color=color, label=c, height=0.62, edgecolor=ps.SURFACE, linewidth=1)
            left += vals
        other = 100 - left
        ax.barh(y, other.clip(min=0), left=left, color="#d9d8d3", label="other", height=0.62,
                edgecolor=ps.SURFACE, linewidth=1)
        ax.set_yticks(y)
        ax.set_yticklabels(layers)
        ax.set_xlim(0, 100)
        ax.set_xlabel("% of cycle samples in the operator's hottest symbol")
        ps.titled(ax, "Which instructions the cycles land on, per operator",
                  "perf annotate (cycles:P) of each standalone operator's hottest symbol")
        ax.legend(ncol=5, loc="upper center", bbox_to_anchor=(0.5, -0.12))
        fig.savefig(plots / "instruction_mix_by_operator.png")
        plt.close(fig)

    # perf mem
    mem = parse_shares(out / "raw" / "mem_by_level.txt", 1)
    if mem:
        L += ["## perf mem: sampled loads by data source (full inference)", "",
              "Load sampling (PEBS load-latency, latency threshold set by perf mem). Shares are of sampled "
              "loads; 'LFB' = line fill buffer (miss already in flight).", "", "| % samples | data source |",
              "|---|---|"]
        L += [f"| {p:.2f} | {d} |" for p, d in mem[:15]]
        L.append("")
    w = parse_shares(out / "raw" / "mem_weight_by_level.txt", 2)
    if w:
        L += ["### Load samples with weight (latency) by level and library", "", "```"]
        L += [f"{p:6.2f}%  {d}" for p, d in w[:25]]
        L += ["```", ""]
    (proc / "INSTRUCTIONS.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[:80]))


if __name__ == "__main__":
    main(sys.argv[1])
